default_platform(:ios)

platform :ios do
  desc "build and send to betatesters..."
  # тут можно логики нагородить, настройки сборки, разделение на таргеты и т.п.
  lane :beta do
    increment_build_number
    build_app
    upload_to_testflight
  end
end
